<style type="text/css">
    /* CSS to ensure at least four cards in a row */
.gallery-items {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

.gallery-item {
    width: calc(25% - 15px); /* Four items in a row with some margin between them */
    margin-bottom: 30px; /* Margin between rows */
}

@media (max-width: 991px) {
    .gallery-item {
        width: calc(33.33% - 15px); /* Three items in a row on smaller screens */
    }
}

@media (max-width: 767px) {
    .gallery-item {
        width: calc(50% - 15px); /* Two items in a row on even smaller screens */
    }
}

@media (max-width: 575px) {
    .gallery-item {
        width: 100%; /* Single item per row on the smallest screens */
    }
}


/*.brand_hover:hover h4 {
  color: red;
}*/

.brand-box {
  object-fit: contain;
  border-radius: 5px;
  border: 2px solid #010028; /* Update border color */
  padding: 8px;
  box-shadow: 1px 1px 1px 1px;
}

</style>
<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8">
<title>GALLERY | BT AUTO REPAIR</title>
<link rel="shortcut icon" href="images/favicon.png">
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/owl.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link href="css/responsive.css" rel="stylesheet">
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body>
<div class="page-wrapper">
 	
 	
    <!-- Main Header -->
    @include('frontend.includes.header')
    <!--End Main Header -->
    
    <!-- Page Banner -->
    <section class="page-banner" style="background-image:url(images/background/page-banner-1.jpg);">
         <div class="auto-container">
            <div class="page-title"><h1>Our Gallery</h1></div>
            <div class="bread-crumb text-right">
                <span class="initial-text">you are here: </span>
                <span class="current">Our Gallery</span>
            </div>
        </div>
	</section>

	<!--Filter Section-->

 <section class="gallery-section">
    <div class="auto-container">
        
        <div class="sec-title">
            <h3 style="font-weight: bold;">Our Gallery</h3>
        </div>
        
        <!-- Gallery Items -->
        <div class="gallery-items">
            @foreach ($pic as $data)
            <article class="gallery-item">
                <figure class="image-box brand-box">
                    <a href="/uploads/gallery/{{ $data->picture }}" class="lightbox-image" title="{{ $data->picture_name }}">
                        <img src="/uploads/gallery/{{ $data->picture }}" alt="" style="height: 200px; object-fit: cover;">
                    </a>
                </figure>
                <a href="/uploads/gallery/{{ $data->picture }}" class="overlay lightbox-image" title="{{ $data->picture_name }}"></a>
                <div class="item-caption">
                    <h4><strong>{{ $data->picture_name }}</strong></h4>
                </div>
            </article>
            @endforeach
        </div>

          <ul class="pagination">
                <li class="current"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
            </ul>

         <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="pq-pagination">
                    <nav aria-label="Page navigation">
                        <ul class="page-numbers">
                            <!-- Pagination links generated by Laravel -->
                            {{ $pic->links() }}
                        </ul>
                    </nav>
                </div>
            </div>
        
    </div>    
</section>





    
    <!--Contact Options-->
    <section class="contact-options">
    	<div class="clearfix">
        	<ul class="info-box clearfix wow bounceInRight">
            	<li><a href="contact.html"><span class="fa fa-calendar"></span> Make an appointment</a></li>
                <li><a href="contact.html"><span class="fa fa-phone"></span> Contact Us</a> </li>
            </ul>
        </div>
    </section>
    
    <!--Main Footer-->
    @include('frontend.includes.footer')
    
</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top"></div>


<script src="js/jquery.js"></script> 
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.mixitup.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.fancybox.pack.js"></script>
<script src="js/wow.js"></script>
<script src="js/script.js"></script>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var $_Tawk_API={},$_Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/569cfc09aeafd72017dd6ea9/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-15521914-3', 'auto');
  ga('send', 'pageview');

</script>

</body>

</html>
